name: Deploy Application
on:
  push:
    branches:
      - feature/issue-6-github-actions
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Docker login
        run: |
          echo ${{ secrets.GH_PACK_KEY }} | docker login https://docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Build image
        run: docker build -t ${{ secrets.REGISTRY_URL }}/currency-exchange:last -f Dockerfile .

      - name: Push image to registry
        run: docker push ${{ secrets.REGISTRY_URL }}/currency-exchange:last
